# Get Values from Zabbix Server
UserParameter=eatonipp.discover, "C:\Program Files\Zabbix Agent 2\scripts\check_eaton_ipp" -c "C:\Program Files\Zabbix Agent 2\scripts\check_eaton_ipp.conf" discover
UserParameter=eatonipp.get[*], "C:\Program Files\Zabbix Agent 2\scripts\check_eaton_ipp" -c "C:\Program Files\Zabbix Agent 2\scripts\check_eaton_ipp.conf" get $1