# Get Values from Zabbix Server
UserParameter=eatonipp.discover, /etc/zabbix/scripts/check_eaton_ipp -c /etc/zabbix/check_eaton_ipp.conf discover
UserParameter=eatonipp.get[*], /etc/zabbix/scripts/check_eaton_ipp -c /etc/zabbix/check_eaton_ipp.conf get $1
